version: '3'
services:
  web:
    image: docker-node-koa-mongoapp
    build: ./web-server
    command: node index.js
    ports:
      - "3000:3000"
    volumes:
      - ./web-server:/app
      - /app/node_modules
    depends_on:
      - "mongo"

  mongo:
    image: 'mongo'
    ports: 
      - "27018:27018"

  # adminmongo: 
  #   image: 'rzolotarev/adminmongo'
  #   ports:
  #     ["1234:1234"]